### ISSUE TITLE
Azure files share

### ISSUE THREAD

**Issue by tormodu** [garvincasimir/Elasticsearch-Azure-PAAS#10]
I have been testing the performance of Elastic Search using the Azure files share persistent storage for Elastic Search indexes and the performance is not good.
I ran two tests one using local storage and one using the file share, both tests indexed 13 million documents. When using local storage indexing took about 45 minutes, using the share it took over 2 hours. 

There should be a config value specifying whether to use local storage or azure files. 
For systems using an external data store to populate the index, there may not be any need for a persistent disk for the index.

**Comment by tormodu** [comment]
It seems like the issue is related to the following error message:

java.io.IOException: An existing connection was forcibly closed by the remote host
	at sun.nio.ch.SocketDispatcher.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(Unknown Source)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(Unknown Source)
	at sun.nio.ch.IOUtil.read(Unknown Source)
	at sun.nio.ch.SocketChannelImpl.read(Unknown Source)
	at org.elasticsearch.common.netty.channel.socket.nio.NioWorker.read(NioWorker.java:64)
	at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108)
	at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:318)
	at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
	at org.elasticsearch.common.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
	at org.elasticsearch.common.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
	at org.elasticsearch.common.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

**Comment by garvincasimir** [comment]
Seems to be an issue with Elasticsearch when communicating with other nodes. The only connections here are between nodes and the client. Strange that it would go away when writing to local disk. Perhaps, one of the nodes is locking up while rapidly writing to the file share. Could there be a performance counter we are neglecting to look into?

**Comment by garvincasimir** [comment]
Also, although I don't think we should abandon the file share, I have been doing some reading and I am leaning more toward the idea of keeping elasticsearch in sync with a primary store such as my bulk import files or some sort of database.

**Comment by garvincasimir** [comment]
Use local store plus data load instead of shares.
